services:
  db:
    image: mysql
    container_name: tcc_dev_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tcc_dev
      - MYSQL_USER=tcc_dev
      - MYSQL_PASSWORD=tcc_dev
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: