FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies with peer dep bypass
RUN npm install --legacy-peer-deps

# Copy all other source code files
COPY . .

# Build application
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
