services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.yml
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev