export const publicRoutes = [
  "/",
  "/login",
  "/register",
  "/verify-email",
  "/forgot-password",
  "/register-email",
  "/register-password",
  "/setup",
  "/setup-settings",
  "/redirect",
  "/recover-password",
  "/api/v1/setup",
  "/api/v1/setup/status",
  "/api/v1/auth/confirm",
  "/api/v1/auth/callback",
  "/api/v1/auth/redirect",
];
